### ISSUE TITLE
Doesn't work on python 3.9

### ISSUE THREAD

**Issue by MilovanovM** [sns-sdks/python-facebook#69]
>So recommend to use the latest version of Python 3.

Hey!
The latest version is 3.9, but the lib doesn't work on it.
When I import `Api` I get the following

```
    from pyfacebook import Api
/usr/local/lib/python3.9/site-packages/pyfacebook/__init__.py:5: in <module>
    from .api import *  # noqa
/usr/local/lib/python3.9/site-packages/pyfacebook/api/__init__.py:1: in <module>
    from .base import BaseApi
/usr/local/lib/python3.9/site-packages/pyfacebook/api/base.py:18: in <module>
    from pyfacebook.models import AccessToken, AuthAccessToken
/usr/local/lib/python3.9/site-packages/pyfacebook/models/__init__.py:1: in <module>
    from .access_token import AccessToken, AuthAccessToken
/usr/local/lib/python3.9/site-packages/pyfacebook/models/access_token.py:7: in <module>
    from .base import BaseModel
/usr/local/lib/python3.9/site-packages/pyfacebook/models/base.py:6: in <module>
    import cattr
/usr/local/lib/python3.9/site-packages/cattr/__init__.py:2: in <module>
    from .converters import Converter, UnstructureStrategy
/usr/local/lib/python3.9/site-packages/cattr/converters.py:15: in <module>
    from ._compat import (
/usr/local/lib/python3.9/site-packages/cattr/_compat.py:87: in <module>
    from typing import _Union
E   ImportError: cannot import name '_Union' from 'typing' (/usr/local/lib/python3.9/typing.py)
```

Is there a way to fix this?

Thanks!

**Comment by tirkarthi** [comment]
This seems to a be an upstream issue in cattrs. This seems to have been fixed in master branch of cattrs. Commit for Python 3.9 support : https://github.com/Tinche/cattrs/commit/eb454d45ee198ef008b92a490ec67e1ed154b26f . This import being removed in https://github.com/Tinche/cattrs/commit/eb454d45ee198ef008b92a490ec67e1ed154b26f#diff-4fdf907a3f8bb76c5a2ead25cbe0cc5ecdbb289e14b03dc2115bece96feddb7eL75

**Comment by MerleLiuKun** [comment]
need to check Tinche/cattrs#88
